version: '3'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=sample
      - MYSQL_ROOT_PASSWORD=whatispwd
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  wiki:
    image: mulspace/mediawiki:1.31
    container_name: wiki
    volumes:
      - wikidata:/var/www/html
    depends_on:
      - mysql
    ports:
      - 9000:80

volumes:
  dbdata:
  wikidata:
